---
output:
  html_document:
    keep_md: yes
---
## Q1

```{r}
library(AppliedPredictiveModeling)
data(segmentationOriginal)
library(caret)

```

```{r}
training <- segmentationOriginal[segmentationOriginal$Case == "Train", ]
testing <- segmentationOriginal[segmentationOriginal$Case == "Test", ]
```

```{r}
library(rattle)
set.seed(125)

modelFit <- train( Class ~ ., data = training, method = "rpart")
predictions <- predict(modelFit, newdata = testing)
confusionMatrix(predictions, testing$Class)
fancyRpartPlot(modelFit$finalModel)
```

## Q3

```{r}
# install.packages('pgmm')
library(pgmm)
data(olive)
olive = olive[,-1]
```

```{r}
modelOliveFit <- train( Area ~ ., data = olive, method = "rpart")
fancyRpartPlot(modelOliveFit$finalModel)
```

```{r}
newdata = as.data.frame(t(colMeans(olive)))
olivePredictions <- predict(modelOliveFit, newdata = newdata)
olivePredictions
```

## Q4

```{r}
# install.packages('ElemStatLearn')
library(ElemStatLearn)
data(SAheart)
set.seed(8484)
train = sample(1:dim(SAheart)[1],size=dim(SAheart)[1]/2,replace=F)
trainSA = SAheart[train,]
testSA = SAheart[-train,]
```

```{r}
set.seed(13234)
modelHeartFit <- train(chd ~ age + alcohol + obesity + tobacco + typea + ldl,
                       data = trainSA,
                       method = "glm",
                       family = "binomial")
modelHeartFit$finalModel
```

```{r}
heartTrainPredictions <- predict(modelHeartFit)
heartPredictions <- predict(modelHeartFit, newdata = testSA)

missClass = function(values,prediction){sum(((prediction > 0.5)*1) != values)/length(values)}
trainingSetMisclassification <- missClass(trainSA$chd, heartTrainPredictions)
testingSetMisclassification <- missClass(testSA$chd, heartPredictions)

trainingSetMisclassification
testingSetMisclassification
```

## Q5

```{r}
library(ElemStatLearn)
data(vowel.train)
data(vowel.test)
```

```{r}
vowel.train$y <- as.factor(vowel.train$y)
vowel.test$y <- as.factor(vowel.test$y)
```

```{r}
set.seed(33833)
vowelModel1 <- train(y ~ . , data = vowel.train, model = "rf", type = 1, importance = FALSE)
vowelModel2 <- train(y ~ . , data = vowel.train, model = "rf", type = 2, importance = FALSE)
varImp(vowelModel1)
varImp(vowelModel2)
```

